# Usage

> Information: If possible, use absolute paths when specifying directories or files.

Example usage (to do a dry-run add the command line flag `-n`):

```
snakemake \
    --directory <output dir> \
    --software-deployment-method conda \
    --directory <output directory> \
    --configfile <path to my config> \
    --workflow-profile profiles/fastq2vcf/ \
    [--conda-prefix </path/to/conda/env/location>] \
    [--profile </path/to/profile/directory>]
```


* `directory`: Specifies where the results are stored.
* `configfile`: The path to the config file that contains e.g. the paths to the genome indices (see [Config file](#config-file)).
* `software-deployment-method`: Software deployment. E.g. conda, apptainer
* `--conda-prefix` (optional): Where should the conda environments be stored.
* `--profile` (optional): Path to a profile specification that defines e.g. which executor to use and how many jobs are submitted in parallel (see section [Configuration](#configuration)).

## Config file

The config file contains variables that configure how the workflow is executed. 
This includes the paths to the reference and indices.

>Note: Make sure to use absolute paths in the config file.

An example config file:

```
# Path to TSV sample sheet
sample_sheet: 'tests/pep/samples.tsv'
sra_mode: false
index_dir: /path/to/reference_files
quant_mode: 'salmon_bam'
interleaved_input: false
bam_input: false
fastq_screen_conf: ''
# Config options for FRASER
fraser:
  min_read: 2
  mapq_filter: 255
# Config options for STAR
star:
  min_read: 2
# Config options for easyquant
requantify:
  interval_mode: true
  allow_mismatches: false
```
