# Configuration

## Running on a HPC-cluster

To execute the workflow on a cluster managed by a workload manager such as SLURM, 
a profile file must be created with specific content tailored to the cluster's 
configuration. The following example profile can be used on a cluster configured
with SLURM. 

```
executor: cluster-generic
cluster-generic-submit-cmd: sbatch -n {threads} --mem={resources.mem_mb} --job-name=smk-{rule} --parsable
cluster-generic-cancel-cmd: scancel
jobs: 100
```

Alternatively, the [`snakemake-executor-plugin-slurm`](https://github.com/snakemake/snakemake-executor-plugin-slurm) can be used to submit
jobs to SLURM. Please check for compatibility with your SLURM setup. Users executing the pipeline must be included in SLURMDB with permissions properly set.

The file has to be located in a directory called e.g. `slurm` and the
file has to be named `config.v8+.yaml`. To use the profile, just call the pipeline
with the parameter `--profile <path/to/slurm_folder>`.
The `jobs` parameter in the profile file specifies the maximum number of jobs that 
Snakemake can submit in parallel. 
When the pipeline is started within a SLURM job, no more than 1 core and 1 GB of 
memory is required for this initial job as all tasks are submitted as individual jobs.
