# Developer guide

## Code structure

The snakemake worflow is written based on the snakemake 
[best practices](https://snakemake.readthedocs.io/en/stable/snakefiles/best_practices.html)
and structured based on the [snakemake workflow template](https://github.com/snakemake-workflows/snakemake-workflow-template).

## Testing

We employ a comprehensive testing strategy that includes both unit tests and 
integration tests for the TronMake pipeline. With this approach we want to
verify individual components as well as the overall workflow. The testing 
framework [pytest-workflow](https://pytest-workflow.readthedocs.io/en/stable/)
is used for this purpose.

When changes are pushed to a branch, the unittests are triggered in the GitLab 
CI. For merge requests to the dev branch or main branch, the unit tests and 
the integration tests are executed. 

**Unit Tests**

Unit tests are designed to test individual functions or modules in isolation.
In the unittests of fastq2vcf, dryruns are carried out in which the syntax 
of the scripts is checked for correctness. This test is completed quickly in 
about 30 seconds.
To run the unit tests execute the following command.

```
make unittest
```

**Integration Tests**

Integration tests verify that different components of the pipeline work together 
as expected. These tests are essential for ensuring the overall functionality of 
the pipeline. The integration tests run the pipeline for a minimal test data set.
This test therefore takes a longer time to run, about 10 minutes.
To run the integration tests execute the following command.

```
make integrationtest
```

**Test run**

To only test the TronMake RNA-splicing workflow execute:

```
make testrun
```
