import os
import sys
import math
import pandas as pd
from pathlib import Path

configfile: workflow.source_path('../config/config.yaml')
configfile: workflow.source_path('../config/container_config.yaml')

include: "rules/common.smk"
include: "rules/import_tronmake_expression.smk"
include: "rules/junctions.smk"
include: "rules/requantify.smk"
include: "rules/assembly.smk"
include: "rules/multiqc.smk"

samples = read_sample_sheet(config['sample_sheet'])

rule all:
    input:
        get_final_output()
    default_target: True
    localrule: True

rule doc_all:
    input:
        "documentation/tronmake-rna-splicing/docs/assets/docstring.md",
        "documentation/tronmake-rna-splicing/docs/assets/software.tsv",

rule docstring_export:
    """
    Export docstrings of snakemake rules into markdown format
    """
    output:
        doctrings_markdown = "documentation/tronmake-rna-splicing/docs/assets/docstring.md",
    log:
        "documentation/tronmake-rna-splicing/docs/assets/export_log.txt"
    params:
        rule_collection = {str(rule.name): str(rule.docstring) for rule in workflow.rules}
    conda: 'envs/python.yaml'
    container:
        config['container'].get('additional_software')
    script:
        'scripts/export_doc.py'

rule software_export:
    """
    Export docstrings of snakemake rules into markdown format
    """
    output:
        software_table = "documentation/tronmake-rna-splicing/docs/assets/software.tsv",
    log:
        "documentation/tronmake-rna-splicing/docs/assets/export_software_log.txt"
    params:
        software_collection = {str(rule.name): 
            {'conda': str(rule.conda_env), 'container': str(rule.container_img) } for rule in workflow.rules}
    conda: 'envs/python.yaml'
    container:
        config['container'].get('additional_software')
    script:
        'scripts/export_software.py'