import os
import sys
import math
import pandas as pd

# Base container image for running jobs
configfile: workflow.source_path('../config/config.yaml')

include: "rules/common.smk"
include: "rules/import_tronmake_expression.smk"
include: "rules/junctions.smk"
include: "rules/requantify.smk"
include: "rules/filtering.smk"

samples = read_sample_sheet(config['sample_sheet'])

rule all:
    input:
        get_final_output()
    default_target: True
    localrule: True
        
