.mkdocs:
  image: condaforge/miniforge3:24.7.1-2
  stage: deploy
  script:
    - mamba create -n mkdocs conda-forge::mkdocs 
    - source /opt/conda/bin/activate mkdocs
    - pip install mkdocs-material
    - mkdocs build -f documentation/tronmake-rna-splicing/mkdocs.yml -d ../../public
  artifacts:
    paths:
      - public

pages:
  extends: .mkdocs
  only:
    - main
    - dev
