name: tronmake
channels:
  - bioconda
  - conda-forge
  - nodefaults
dependencies:
  - snakemake-minimal>=8.4.3
  - pip
  - pandas
  - pip:
    - biopython
    - snakemake-executor-plugin-slurm
    - python-magic
    - loguru
