rule samtools_index:
    """
    Index alignment generated by STAR

    input:
        bam (str): Path to coordinate sorted BAM file
    output:
        bai (str): Path to binary index of BAM file
    """
    input:
        rules.tronmake_expression_star.output.alignment,
    output:
        "results/{sample}/star/Aligned.sortedByCoord.out.bam.bai"
    params:
        extra="",  # optional params string
    threads: 1  # This value - 1 will be sent to -@
    wrapper:
        "v3.14.0/bio/samtools/index"

rule fraser:
    """FRASER
    
    Run FRASER on each sample to calculate PSI and Intron Jaccard Index of splice junctions

    input:
        bam (str): Alignment (BAM sorted by coordinated)
        bai (str): Alignment index (BAM sorted by coordinated)
        gtf (str): Reference transcript model in GTF format

    output:
        psi_table (str): Splice junction annotated with intron usage

    params:
        working_dir (str): Working directory for fraser functions
        min_read (int): Minimum number of reads to count splice junction. Defaults to 5
        mapq_filter (int): Mapping quality filter to discard low quality alignments in calculations. Defaults to 255
        exe (str): Path to FRASER wrapper script
    """

    input:
        bam = rules.tronmake_expression_star.output.alignment,
        bai = rules.samtools_index.output,
        gtf = os.path.join(config['index_dir'], 'ref_annot.gtf')
    params:
        working_dir = 
            lambda wildcards, output: os.path.dirname(output.psi_table),
        min_read = config['fraser'].get('min_read', 5),
        mapq_filter = config['fraser'].get('mapq_filter', 255),
        exe = workflow.source_path('../scripts/fraser.R')
    log:  "results/{sample}/log/fraser.log"
    output:
        psi_table = "results/{sample}/fraser/junctions_psi.tsv"
    threads: 2
    resources:
        mem_mb = 16000
    conda: '../envs/fraser.yaml'
    shell:
        'Rscript --vanilla {params.exe} '
        '--bam {input.bam} '
        '--threads {threads} '
        '--output_table {output.psi_table} '
        '--strandedness 0 '
        '--min_expression {params.min_read} '
        '--mapq {params.mapq_filter} 2>&1 | tee {log}'

rule parse_junctions:
    """Parse junctions

    Rule to parse STAR and FRASER results into standardized splice junction format based on genomic
    coordinates.

    input:
        star_sj (str): Path to STAR high confidence SJ.out.tab
        fraser_psi (str): Path to FRASER metric table
        canonical_junctions (str): Path to canonical junction filter file

    output:
        parsed_sj_tmp (str): Path to parsed junction table
    
    params:
        exe (str): Path to R wrapper script
        read_support (int): Minimum number of unique alignments to report junction. Defaults to 5

    """
    input:
        star_sj = rules.tronmake_expression_star.output.sj,
        fraser_psi = rules.fraser.output.psi_table,
        canonical_junctions = os.path.join(config['index_dir'], 'canonical_junctions.tsv')
    output:
        parsed_sj_tmp = temp("results/{sample}/fetchdata/parsed_sj.tsv.tmp"),
        removed_junction = "results/{sample}/fetchdata/sj_canonical.tsv"
    params:
        exe = workflow.source_path('../scripts/parse_junctions.R'),
        read_support = config['fraser'].get('min_read', 5),
        working_dir = 
            lambda wildcards, output: os.path.dirname(output.parsed_sj_tmp),
    log: "results/{sample}/log/sj_parsing.log"
    threads: 1
    resources:
        mem_mb = 8000
    conda: '../envs/R.yaml'
    shell:
        'Rscript --vanilla {params.exe} '
        '--sj {input.star_sj} '
        '--canonical_junctions {input.canonical_junctions} '
        '--fraser {input.fraser_psi} '
        '--read_support {params.read_support} '
        '--output {params.working_dir} 2>&1 | tee {log}'

rule calculate_junction_cpm:
    """CPM calculation

    Rule to normalize raw splice junction counts obtained by STAR
    using count per million (CPM) metric. This rule normalizes
    the uniquely mapped reads (jCPM_uniquely_mapped), multi mapped
    reads (jCPM_multi_mapped) and total (uniquely and multi) mapped 
    reads (jCPM_total_mapped).

    input:
        star_sj (str): Path to STAR high confidence SJ.out.tab

    output:
        star_sj_cpm (str): Path to normalised SJ counts

    params:
       exe (str): Path to python script 

    """
    input:
        star_sj = rules.tronmake_expression_star.output.sj
    output:
        star_sj_cpm = "results/{sample}/fetchdata/sj_out_tab_cpm.tsv"
    params:
        exe = workflow.source_path('../scripts/normalize_star_cpm.py')
    log: "results/{sample}/log/sj_cpm.log"
    threads: 1
    resources:
        mem_mb = 4000
    conda: '../envs/python.yaml'
    shell:
        'python {params.exe} '
        '-i {input.star_sj} '
        '-o {output.star_sj_cpm} 2>&1 | tee {log}'


rule filter_mapability:
    """Mapability filter

    Rule to filter junctions located in problematic regions. Problematic regions
    are defined by UCSC and ENCODE lists. These regions are defined as problematic,
    as short-read experiments can not be unambigously mapped to these locations.

    input:
        parsed_sj (str): Path to parsed splice junction table.
        encode_regions (str): Path to ENCODE blacklist
        ucsc_regions (str): Path to UCSC problematic regions

    output:
        parsed_sj (str): Path to parsed junction table.
        failed_sj (str): Path to junction table overlapping problematic region.
    
    params:
        exe (str): Path to R wrapper script
    """
    input:
        parsed_sj = rules.parse_junctions.output.parsed_sj_tmp,
        encode_regions = os.path.join(config['index_dir'], 'mapability', 'encode_blacklist.bed'),
        ucsc_regions = os.path.join(config['index_dir'], 'mapability', 'ucsc_unusal.bed')
    output:
        parsed_sj = temp("results/{sample}/fetchdata/parsed_sj.tsv"),
        failed_sj = "results/{sample}/fetchdata/sj_problematic_mapability.tsv"
    threads: 1
    resources:
        mem_mb = 8000
    params:
        exe =  workflow.source_path('../scripts/filter_mapability.R')
    conda: '../envs/R.yaml'
    log:  "results/{sample}/log/mapability_filter.log"
    shell:
        'Rscript --vanilla {params.exe} '
        '--sj {input.parsed_sj} '
        '--encode_blacklist {input.encode_regions} '
        '--ucsc_unusual {input.ucsc_regions} '
        '--output {output.parsed_sj} '
        '--removed_output {output.failed_sj} 2>&1 | tee {log} '

rule add_context_sequence:
    """Add transcript sequence

    Rule to annotate splice junction candidates with possible transcript sequences.
    Junctions without gene or transcript overlap are removed in this step. Moreover,
    junctions falling in genes defined in a custom exclusion list can be removed in this
    step. Default genes removed in this step are IG^, TCR^, BCR^ and HLA.

    input:
        parsed_sj (str):  Path to splice junction table.
        transcripts (str): Path to RDS object of reference transcripts.
        genome (str): Path to 2Bit object of reference genome.
        tx2gene (str): Path to transcript to gene mapping.
        gene2hgnc (str): Path to gene to HGNC (gene name) mapping.
        gene_exclusion (str): Path to gene exclusion list. Needs to contain tidyverse 
            compatible regex representation of genes to exclude
    output:
        annotated_sj (str): Path to splice junction table with context sequences.
        annotated_sj_problematic (str): Path to table with removed junctions.
    params:
        exe (str): Path to R wrapper script

    """
    input:
        parsed_sj = rules.filter_mapability.output.parsed_sj,
        transcripts = os.path.join(config['index_dir'], 'ref_transcripts.RDS'),
        genome = os.path.join(config['index_dir'], 'hg38.analysisSet.2bit'),
        tx2gene = os.path.join(config['index_dir'], 'tx2gene.tsv'),
        gene2hgnc = os.path.join(config['index_dir'], 'hgnc_ensembl_id_gencode46.gz'),
        gene_exclusion = os.path.join(config['index_dir'], 'exclusion_pattern.tsv')
    output:
        annotated_sj = temp("results/{sample}/fetchdata/annotated_sj.tsv"),
        annotated_sj_problematic = "results/{sample}/fetchdata/sj_problematic_gene_no_transcript_overlap.tsv"
    threads: 1
    resources:
        mem_mb = 20000
    params:
        exe = workflow.source_path('../scripts/add_tx.R')
    conda: '../envs/R.yaml'
    log:  "results/{sample}/log/add_cts.log"
    shell:
        'Rscript --vanilla {params.exe} '
        '--juncs {input.parsed_sj} '
        '--transcripts {input.transcripts} '
        '--genome {input.genome} '
        '--tx2gene {input.tx2gene} '
        '--gene_exclusion {input.gene_exclusion} '
        '--gene2hgnc {input.gene2hgnc} '
        '--output {output.annotated_sj} '
        '--removed_output {output.annotated_sj_problematic} 2>&1 | tee {log}'

rule add_transcript_expression:
    """Add transcript/gene expression

    Rule to annotate splice junction candidate with transcript and gene expression
    determined with salmon.

    input:
        annotated_sj (str):  Path to splice junction table.
        transcript_expression (str): Path to salmon transcript level quantification.
        gene_expression (str): Path to salmon gene level quantification.
        junction_expression (str): Path to CPM normalised splice junction counts.
    output:
        sj_expression (str): Path to splice junction table with expression estimates added.
    params:
        exe (str): Path to R wrapper script

    """
    input:
        annotated_sj = rules.add_context_sequence.output.annotated_sj,
        transcript_expression =  'results/{sample}/salmon_bam/quant.sf',
        gene_expression = 'results/{sample}/salmon_bam/quant.genes.sf',
        junction_expression = rules.calculate_junction_cpm.output.star_sj_cpm
    output:
        sj_expression = temp("results/{sample}/fetchdata/annotated_sj_expression.tsv")
    params:
        exe = workflow.source_path('../scripts/add_tpm.R')
    threads: 1
    resources:
        mem_mb = 8000
    conda: '../envs/R.yaml'
    log:  "results/{sample}/log/add_expression_estimates.log"
    shell:
        'Rscript --vanilla {params.exe} '
        '--sj {input.annotated_sj} '
        '--txp {input.transcript_expression} '
        '--gxp {input.gene_expression} '
        '--jxp {input.junction_expression} '
        '--output {output.sj_expression} 2>&1 | tee {log}'

#
#rule ctat_splicing:
#    input:
#        sj_out = "results/{sample}/star/SJ.out.tab",
#        chim_junc = "results/{sample}/star/Chimeric.out.junction"
#    output:
#        introns = "results/{sample}/ctat_splicing/{sample}.introns",
#        cancer_introns = "results/{sample}/ctat_splicing/{sample}.cancer.introns"
#    params:
#        prefix = lambda wildcards, output: output.introns.rstrip(".introns"),
#        genome_lib = config['ctat'].get('genome_lib')
#    shell:
#        'python STAR_to_cancer_introns.py '
#        '--ctat_genome_lib {params.genome_lib} '
#        '--SJ_tab_file {input.sj_out} '
#        '--chimJ_file {input.chim_junc} '
#        '--output_prefix {params.prefix } 2>&1 | tee {log}'

