site_name: TronMake Cancer RNA-splicing
nav: 
  - Home: index.md
  - Installation: installation.md
  - Input: input.md
  - Usage: usage.md
  - Cluster execution: cluster.md
  - Workflow rules: rules.md
  - References: references.md
  - About: about.md
theme:
  name: material
  palette:
    scheme: slate
    primary: teal
    accent: teal
  icon:
    repo: fontawesome/brands/gitlab
    logo: assets/tron.svg
  features:
    - navigation.sections
    - navigation.tabs

copyright: © TRON gGmbH, 2024. This work is licensed under MIT.

repo_url: https://gitlab.rlp.net/tron/tronmake-rna-splicing
plugins:
  - search
  - table-reader
  - include-markdown
