site_name: TronMake Cancer RNA-splicing
site_author: Johannes Hausmann
nav: 
  - Home: index.md
  - Installation: installation.md
  - Input: input.md
  - Usage: usage.md
  - Cluster execution: cluster.md
  - Workflow rules: rules.md
  - References: references.md
  - About: about.md
theme:
  logo: assets/tron.svg
  name: material
  palette:
    scheme: slate
    primary: teal
    accent: teal
  icon:
    repo: fontawesome/brands/gitlab
  features:
    - navigation.sections
    - navigation.tabs
    - toc.integrate 

copyright: © TRON gGmbH, 2024. This work is licensed under MIT.

repo_url: https://gitlab.rlp.net/tron/tronmake-rna-splicing
plugins:
  - search
  - table-reader
  - include-markdown
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: slide
      width: 100%
      height: auto
      zoomable: true
      draggable: true
      skip_classes:
        - custom-skip-class-name
      auto_caption: false
      caption_position: bottom
      background: white
      shadow: true
      manual: false
  - inline-svg

