sample_sheet: 'tests/pep/samples.tsv'
sra_mode: false
index_dir: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
interleaved_input: false
bam_input: false
fraser:
  min_read: 2
  mapq_filter: 255
star:
  min_read: 2
requantify:
  interval_mode: true
  allow_mismatches: false
  bowtie_k_threshold: 200