jobs: 16
local-cores: 16
latency-wait: 120
keep-going: True
printshellcmds: True
rerun-incomplete: True
default-resources:
  mem_mb: 4096
  threads: 4
  runtime: 3600

set-threads:
  salmon: 4
  qualimap: 4
  star: 18
  fastp: 4
  bedGraphToBigWig: 1
  get_fastq_SRA: 2
  samtools_index: 1
  fraser: 4
  parse_junctions: 1
  filter_mapability: 1
  add_context_sequence: 1
  add_transcript_expression: 1
  prepare_requant: 1
  generate_context_fa: 1
  bowtie_index: 4
  bowtie_align: 8
  requantify: 1
  add_quant_counts: 1
  find_cts_matching_wt: 8

set-resources:
  salmon:
    mem_mb: 16000 + ((attempt - 1) * 10000)
    runtime: "1h"
  qualimap:
    mem_mb: 16000 + ((attempt - 1) * 5000)
    runtime: "1h"
  star:
    mem_mb: 48000 + ((attempt - 1) * 10000)
    runtime: "8h"
  fastp:
    mem_mb: 8000 + ((attempt - 1) * 5000)
    runtime: "1h"
  bedGraphToBigWig:
    mem_mb: 4000 + ((attempt - 1) * 2000)
    runtime: "1h"
  get_fastq_SRA:
    mem_mb: 8000 + ((attempt - 1) * 2000)
    runtime: "2h"
  samtools_index:
    mem_mb: 2000 + ((attempt - 1) * 500)
    runtime: "1h"
  fraser:
    mem_mb: 16000 + ((attempt - 1) * 10000)
    runtime: "1h"
  parse_junctions:
    mem_mb: 8000 * attempt
    runtime: "1h"
  filter_mapability:
    mem_mb: 8000 * attempt
    runtime: "1h"
  add_context_sequence:
    mem_mb: 16000 + ((attempt - 1) * 10000)
    runtime: "4h"
  add_transcript_expression:
    mem_mb: 4000 + ((attempt - 1) * 2000)
    runtime: "1h"
  prepare_requant:
    mem_mb: 4000 + ((attempt - 1) * 2000)
    runtime: "1h"
  generate_context_fa:
    mem_mb: 4000 + ((attempt - 1) * 2000)
    runtime: "1h"
  bowtie_index:
    mem_mb: 8000 + ((attempt - 1) * 2000)
    runtime: "1h"
  bowtie_align:
    mem_mb: 16000 + ((attempt - 1) * 10000)
    runtime: "4h"
  requantify:
    mem_mb: 8000 + ((attempt - 1) * 2000)
    runtime: "4h"
  add_quant_counts:
    mem_mb: 4000 * attempt
    runtime: "1h"
  find_cts_matching_wt:
    mem_mb: 16000
    runtime: "4h"
