site_name: NeoRasp
site_author: Johannes Hausmann
nav: 
  - Home: index.md
  - Installation: installation.md
  - Input: input.md
  - Output: output.md
  - Usage: usage.md
  - Cluster execution: cluster.md
  - Workflow rules: rules.md
  - Developer guide: developer_guide.md
  - References: references.md
  - About: about.md
  - FAQ: faq.md
theme:
  logo: assets/tron.svg
  name: material
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.sections
    - navigation.tabs
    - toc.integrate
  palette:
    # Palette toggle for light mode 
    - scheme: default
      primary: blue grey
      accent: pink
      toggle:
        icon: material/lightbulb-on
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: blue grey
      accent: pink
      toggle:
        icon: material/weather-night
        name: Switch to light mode


copyright: © TRON gGmbH, 2026. This work is licensed under MIT.

repo_url: https://github.com/TRON-Bioinformatics/neorasp
plugins:
  - search
  - table-reader
  - include-markdown

markdown_extensions:
  - attr_list
