name: Build and Deploy MkDocs to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v5

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-version: latest
          auto-update-conda: true
          channels: conda-forge,bioconda
          environment-file: environment.yaml
          activate-environment: tronmake
          use-mamba: true

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y libmagic1 graphviz

      - name: Trust Git directory
        run: git config --global --add safe.directory "$(pwd)"

      - name: Clone Snakevision and install requirements
        shell: bash -l {0}
        run: |
          git clone https://github.com/OpenOmics/snakevision.git
          pip install -r snakevision/requirements.txt

      - name: Build rulegraph and run Snakevision
        shell: bash -l {0}
        run: |
          snakemake --configfile tests/splicing.yaml --rulegraph --forceall > documentation/tronmake-rna-splicing/docs/assets/pipeline_rulegraph.dot
          ./snakevision/bin/snakevision -s all doc_all docstring_export software_export \
            -o documentation/tronmake-rna-splicing/docs/assets/pipeline_rulegraph.svg \
            documentation/tronmake-rna-splicing/docs/assets/pipeline_rulegraph.dot

      - name: Run Snakemake documentation build
        shell: bash -l {0}
        run: |
          snakemake -p --until doc_all --configfile tests/splicing.yaml

      - name: Build MkDocs site
        shell: bash -l {0}
        run: |
          mkdocs build -f documentation/tronmake-rna-splicing/mkdocs.yml -d site

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
